# Generated by Django 4.1.4 on 2023-07-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=250)),
                ('profile_content', models.TextField()),
                ('profile_img', models.ImageField(upload_to='profile_images/')),
            ],
        ),
    ]
