# Generated by Django 4.1.4 on 2023-07-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profilemode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileMode',
        ),
    ]
