# Generated by Django 4.1.4 on 2023-07-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_fistname_usermodel_firstname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
