# Generated by Django 4.1.4 on 2023-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmode',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
