# Generated by Django 5.0.1 on 2024-02-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogmode_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmode',
            options={'ordering': ['-pub_date']},
        ),
    ]
