# Generated by Django 5.0.1 on 2024-02-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_secondblogmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondblogmode',
            name='img',
            field=models.ImageField(upload_to='images2/'),
        ),
    ]
